name: CI

on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  Test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: swift:5.8.1-jammy
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          swift test --enable-code-coverage
          
      - name: Generate coverage report
        run: |
          llvm-cov report $(find . | grep xctest) -instr-profile=$(find . | grep profdata) -ignore-filename-regex=".build"
          llvm-cov export $(find . | grep xctest) -instr-profile=$(find . | grep profdata) -ignore-filename-regex=".build" -format=lcov > coverage.lcov

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.lcov
          fail_ci_if_error: true
