name: CI

on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  Test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-last
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          swift test
