name: CI

on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  Test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          swift test --enable-code-coverage
          cp $(swift test --show-codecov-path) ./coverage.json

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.json
          fail_ci_if_error: true
